load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "bazel",
    srcs = ["env.go"],
    importpath = "github.com/dropbox/dbx_build_tools/build_tools/bazel",
    visibility = ["//visibility:public"],
)
